import { toUserOnboardingPayload } from "@/lib/user-onboarding";

export const buildCompletePayload = (state) => {
  const payload = toUserOnboardingPayload({
    firstName: state.firstName,
    lastName: state.lastName,
    gender: state.gender,
    age: state.age,
    height: state.height,
    currentWeight: state.currentWeight,
    goal: state.goal,
    weightGoal: state.weightGoal,
    goals: state.goals,
    targetWeight: state.targetWeight,
    weeklyPace: state.weeklyPace,
    activityLevel: state.activityLevel,
    mealFrequency: state.mealFrequency,
    allergyIds: state.allergyIds?.length
      ? state.allergyIds
      : state.allergyIngredientIds,
    allergyIngredientIds: state.allergyIngredientIds,
    customAllergies: state.customAllergies,
    dietRequirementIds: state.dietRequirementIds,
    customDietRequirements: state.customDietRequirements,
    preferredCuisineIds: state.preferredCuisineIds,
    customPreferredCuisines: state.customPreferredCuisines,
    dislikedFoodIds: state.dislikedFoodIds,
    customDislikedFoods: state.customDislikedFoods,
    preferredIngredientIds: state.preferredIngredientIds,
    customPreferredIngredients: state.customPreferredIngredients,
    dislikedIngredientIds: state.dislikedIngredientIds,
    customDislikedIngredients: state.customDislikedIngredients,
    nutritionPreferenceKeys: state.nutritionPreferenceKeys,
    healthConstraints: state.healthConstraints,
    customHealthConstraints: state.customHealthConstraints,
  });

  return {
    ...payload,
    foodBudget: null,
    foodBudgetTier: null,
    budgetPeriod: null,
    budgetCurrency: "UZS",
    preferredCuisineIds: [],
    customPreferredCuisines: [],
    dislikedFoodIds: [],
    customDislikedFoods: [],
    preferredIngredientIds: [],
    dislikedIngredientIds: [],
    customPreferredIngredients: [],
    customDislikedIngredients: [],
    dislikedOtherText: null,
    weeklyWorkoutCount: 0,
    workoutLocation: null,
    equipmentIds: [],
    customEquipment: [],
    workoutBodyPartIds: [],
    customWorkoutBodyParts: [],
    preferredExerciseIds: [],
    dislikedExerciseIds: [],
    customPreferredExercises: [],
    customDislikedExercises: [],
    completed: true,
  };
};
